from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1680, 1050))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1500, 900))
        self.tabWidget.setMinimumSize(QtCore.QSize(1400, 800))
        self.tabWidget.setMaximumSize(QtCore.QSize(1680, 1050))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 791, 821))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_5_obj_name = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5_obj_name.setGeometry(QtCore.QRect(260, 50, 521, 30))
        self.lineEdit_5_obj_name.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_5_obj_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5_obj_name.setObjectName("lineEdit_5_obj_name")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 231, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 400, 50))
        self.label_2.setObjectName("label_2")
        self.lineEdit_6_t_n = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6_t_n.setGeometry(QtCore.QRect(480, 120, 110, 40))
        self.lineEdit_6_t_n.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_6_t_n.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6_t_n.setObjectName("lineEdit_6_t_n")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 640, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 250, 202, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(230, 250, 108, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_11_pol_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_11_pol_1.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_11_pol_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11_pol_1.setObjectName("lineEdit_11_pol_1")
        self.verticalLayout_2.addWidget(self.lineEdit_11_pol_1)
        self.lineEdit_7_pol_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_7_pol_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_7_pol_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7_pol_3.setObjectName("lineEdit_7_pol_3")
        self.verticalLayout_2.addWidget(self.lineEdit_7_pol_3)
        self.lineEdit_9_ns = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_9_ns.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_9_ns.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9_ns.setObjectName("lineEdit_9_ns")
        self.verticalLayout_2.addWidget(self.lineEdit_9_ns)
        self.lineEdit_12_wind = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_12_wind.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_12_wind.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12_wind.setObjectName("lineEdit_12_wind")
        self.verticalLayout_2.addWidget(self.lineEdit_12_wind)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(360, 250, 162, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(550, 250, 108, 181))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_13_pol_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_13_pol_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_13_pol_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13_pol_2.setObjectName("lineEdit_13_pol_2")
        self.verticalLayout_4.addWidget(self.lineEdit_13_pol_2)
        self.lineEdit_14_pol_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_14_pol_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_14_pol_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14_pol_4.setObjectName("lineEdit_14_pol_4")
        self.verticalLayout_4.addWidget(self.lineEdit_14_pol_4)
        self.lineEdit_15_kr = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_15_kr.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_15_kr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15_kr.setObjectName("lineEdit_15_kr")
        self.verticalLayout_4.addWidget(self.lineEdit_15_kr)
        self.lineEdit_16_door = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_16_door.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_16_door.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16_door.setObjectName("lineEdit_16_door")
        self.verticalLayout_4.addWidget(self.lineEdit_16_door)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 510, 510, 30))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(49, 560, 21, 30))
        self.label_7.setObjectName("label_7")
        self.comboBox_t1 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_t1.setGeometry(QtCore.QRect(80, 560, 80, 30))
        self.comboBox_t1.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.comboBox_t1.setObjectName("comboBox_t1")
        self.comboBox_t1.addItem("")
        self.comboBox_t1.addItem("")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(200, 560, 20, 30))
        self.label_14.setObjectName("label_14")
        self.comboBox_2_t2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2_t2.setGeometry(QtCore.QRect(230, 560, 80, 30))
        self.comboBox_2_t2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.comboBox_2_t2.setObjectName("comboBox_2_t2")
        self.comboBox_2_t2.addItem("")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 740, 160, 30))
        self.label_15.setObjectName("label_15")
        self.comboBox_3_tube = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3_tube.setGeometry(QtCore.QRect(200, 740, 171, 30))
        self.comboBox_3_tube.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.comboBox_3_tube.setObjectName("comboBox_3_tube")
        self.comboBox_3_tube.addItem("")
        self.comboBox_3_tube.addItem("")
        self.checkBox_3_n_coef = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3_n_coef.setGeometry(QtCore.QRect(40, 460, 561, 31))
        self.checkBox_3_n_coef.setObjectName("checkBox_3_n_coef")
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(20, 620, 521, 30))
        self.label_40.setObjectName("label_40")
        self.lineEdit_p_n = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_p_n.setGeometry(QtCore.QRect(69, 670, 91, 31))
        self.lineEdit_p_n.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_p_n.setText("")
        self.lineEdit_p_n.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_p_n.setObjectName("lineEdit_p_n")
        self.comboBox_4_p_n = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4_p_n.setGeometry(QtCore.QRect(190, 670, 111, 31))
        self.comboBox_4_p_n.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.comboBox_4_p_n.setObjectName("comboBox_4_p_n")
        self.comboBox_4_p_n.addItem("")
        self.comboBox_4_p_n.addItem("")
        self.comboBox_4_p_n.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(820, 10, 661, 301))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 431, 231))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(480, 50, 160, 241))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_17_sum_h_loss = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_17_sum_h_loss.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_17_sum_h_loss.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17_sum_h_loss.setReadOnly(True)
        self.lineEdit_17_sum_h_loss.setObjectName("lineEdit_17_sum_h_loss")
        self.verticalLayout_6.addWidget(self.lineEdit_17_sum_h_loss)
        self.lineEdit_18_sum_heat = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_18_sum_heat.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_18_sum_heat.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18_sum_heat.setReadOnly(True)
        self.lineEdit_18_sum_heat.setObjectName("lineEdit_18_sum_heat")
        self.verticalLayout_6.addWidget(self.lineEdit_18_sum_heat)
        self.lineEdit_20_sum_rate = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_20_sum_rate.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_20_sum_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20_sum_rate.setReadOnly(True)
        self.lineEdit_20_sum_rate.setObjectName("lineEdit_20_sum_rate")
        self.verticalLayout_6.addWidget(self.lineEdit_20_sum_rate)
        self.lineEdit_19_name_gck = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_19_name_gck.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_19_name_gck.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19_name_gck.setReadOnly(True)
        self.lineEdit_19_name_gck.setObjectName("lineEdit_19_name_gck")
        self.verticalLayout_6.addWidget(self.lineEdit_19_name_gck)
        self.lineEdit_21_sum_p_loss = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_21_sum_p_loss.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_21_sum_p_loss.setText("")
        self.lineEdit_21_sum_p_loss.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21_sum_p_loss.setReadOnly(True)
        self.lineEdit_21_sum_p_loss.setObjectName("lineEdit_21_sum_p_loss")
        self.verticalLayout_6.addWidget(self.lineEdit_21_sum_p_loss)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(820, 320, 661, 261))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 50, 442, 181))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_7.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_7.addWidget(self.label_27)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(480, 50, 160, 181))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_22_sum_n_heat = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_22_sum_n_heat.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_22_sum_n_heat.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22_sum_n_heat.setReadOnly(True)
        self.lineEdit_22_sum_n_heat.setObjectName("lineEdit_22_sum_n_heat")
        self.verticalLayout_8.addWidget(self.lineEdit_22_sum_n_heat)
        self.lineEdit_23_dl_heat = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_23_dl_heat.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_23_dl_heat.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23_dl_heat.setReadOnly(True)
        self.lineEdit_23_dl_heat.setObjectName("lineEdit_23_dl_heat")
        self.verticalLayout_8.addWidget(self.lineEdit_23_dl_heat)
        self.lineEdit_24_n_rate = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_24_n_rate.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_24_n_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24_n_rate.setReadOnly(True)
        self.lineEdit_24_n_rate.setObjectName("lineEdit_24_n_rate")
        self.verticalLayout_8.addWidget(self.lineEdit_24_n_rate)
        self.lineEdit_25_dl_rate = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_25_dl_rate.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_25_dl_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25_dl_rate.setReadOnly(True)
        self.lineEdit_25_dl_rate.setObjectName("lineEdit_25_dl_rate")
        self.verticalLayout_8.addWidget(self.lineEdit_25_dl_rate)
        self.pushButton_5_rest = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5_rest.setGeometry(QtCore.QRect(900, 650, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_5_rest.setFont(font)
        self.pushButton_5_rest.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_5_rest.setObjectName("pushButton_5_rest")
        self.pushButton_6_save = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6_save.setGeometry(QtCore.QRect(1200, 650, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_6_save.setFont(font)
        self.pushButton_6_save.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_6_save.setObjectName("pushButton_6_save")
        self.pushButton_7_help = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7_help.setGeometry(QtCore.QRect(980, 760, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_7_help.setFont(font)
        self.pushButton_7_help.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_7_help.setObjectName("pushButton_7_help")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1270, 850))
        self.tableWidget.setMinimumSize(QtCore.QSize(1250, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(1680, 1050))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.pushButton_add_row = QtWidgets.QPushButton(self.tab)
        self.pushButton_add_row.setGeometry(QtCore.QRect(1320, 210, 140, 70))
        self.pushButton_add_row.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_add_row.setObjectName("pushButton_add_row")
        self.pushButton_2_room = QtWidgets.QPushButton(self.tab)
        self.pushButton_2_room.setGeometry(QtCore.QRect(1320, 40, 140, 70))
        self.pushButton_2_room.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_2_room.setObjectName("pushButton_2_room")
        self.pushButton_3_del_row = QtWidgets.QPushButton(self.tab)
        self.pushButton_3_del_row.setGeometry(QtCore.QRect(1320, 400, 140, 70))
        self.pushButton_3_del_row.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_3_del_row.setObjectName("pushButton_3_del_row")
        self.lineEdit_f_d_row = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_f_d_row.setGeometry(QtCore.QRect(1310, 500, 70, 40))
        self.lineEdit_f_d_row.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_f_d_row.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_f_d_row.setObjectName("lineEdit_f_d_row")
        self.lineEdit_2_l_d_row = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2_l_d_row.setGeometry(QtCore.QRect(1410, 500, 70, 40))
        self.lineEdit_2_l_d_row.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_2_l_d_row.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_l_d_row.setObjectName("lineEdit_2_l_d_row")
        self.pushButton_4_calc_h_loss = QtWidgets.QPushButton(self.tab)
        self.pushButton_4_calc_h_loss.setGeometry(QtCore.QRect(1320, 760, 140, 70))
        self.pushButton_4_calc_h_loss.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_4_calc_h_loss.setObjectName("pushButton_4_calc_h_loss")
        self.lineEdit_3_add_row = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3_add_row.setGeometry(QtCore.QRect(1350, 300, 70, 40))
        self.lineEdit_3_add_row.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_3_add_row.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_add_row.setObjectName("lineEdit_3_add_row")
        self.lineEdit_4_room = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4_room.setGeometry(QtCore.QRect(1350, 130, 70, 40))
        self.lineEdit_4_room.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_4_room.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4_room.setObjectName("lineEdit_4_room")
        self.checkBox_inf = QtWidgets.QCheckBox(self.tab)
        self.checkBox_inf.setGeometry(QtCore.QRect(1290, 570, 201, 51))
        self.checkBox_inf.setObjectName("checkBox_inf")
        self.checkBox_2_t_reg = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2_t_reg.setGeometry(QtCore.QRect(1290, 650, 201, 71))
        self.checkBox_2_t_reg.setObjectName("checkBox_2_t_reg")
        self.pushButton_add_row.raise_()
        self.pushButton_2_room.raise_()
        self.tableWidget.raise_()
        self.pushButton_3_del_row.raise_()
        self.lineEdit_f_d_row.raise_()
        self.lineEdit_2_l_d_row.raise_()
        self.pushButton_4_calc_h_loss.raise_()
        self.lineEdit_3_add_row.raise_()
        self.lineEdit_4_room.raise_()
        self.checkBox_inf.raise_()
        self.checkBox_2_t_reg.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 1270, 850))
        self.tableWidget_2.setMinimumSize(QtCore.QSize(1250, 0))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(1680, 1050))
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(40)
        self.pushButton_form_pr = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_form_pr.setGeometry(QtCore.QRect(1320, 40, 140, 70))
        self.pushButton_form_pr.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_form_pr.setObjectName("pushButton_form_pr")
        self.pushButton_del_pr = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_del_pr.setGeometry(QtCore.QRect(1320, 160, 140, 70))
        self.pushButton_del_pr.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_del_pr.setObjectName("pushButton_del_pr")
        self.pushButton_calc_pr = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_calc_pr.setGeometry(QtCore.QRect(1320, 280, 140, 70))
        self.pushButton_calc_pr.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_calc_pr.setObjectName("pushButton_calc_pr")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Расчет систем отопления"))
        self.groupBox.setTitle(_translate("MainWindow", "Исходные данные"))
        self.label.setText(_translate("MainWindow", "1. Наименование объекта"))
        self.label_2.setText(_translate("MainWindow", "2. Расчетная температура наружного воздуха \n"
"    в холодный период, °C "))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>3. Коэффициенты теплопередачи ограждающих конструкций, Вт/м<span style=\" vertical-align:super;\">2 </span><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:14pt;\">‧ </span>°C </p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "- Пол I зоны"))
        self.label_6.setText(_translate("MainWindow", "- Пол III зоны"))
        self.label_8.setText(_translate("MainWindow", "- Наружняя стена"))
        self.label_9.setText(_translate("MainWindow", "- Окно"))
        self.label_10.setText(_translate("MainWindow", "- Пол II зоны"))
        self.label_11.setText(_translate("MainWindow", "- Пол IV зоны"))
        self.label_12.setText(_translate("MainWindow", "- Кровля"))
        self.label_13.setText(_translate("MainWindow", "- Дверь"))
        self.label_5.setText(_translate("MainWindow", "4. Температура в подающем и обратном трубопроводе, °C"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">t</span><span style=\" font-size:14pt; vertical-align:sub;\">1</span></p></body></html>"))
        self.comboBox_t1.setItemText(0, _translate("MainWindow", "90"))
        self.comboBox_t1.setItemText(1, _translate("MainWindow", "95"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">t</span><span style=\" font-size:14pt; vertical-align:sub;\">2</span></p></body></html>"))
        self.comboBox_2_t2.setItemText(0, _translate("MainWindow", "70"))
        self.label_15.setText(_translate("MainWindow", "6. Материал труб"))
        self.comboBox_3_tube.setItemText(0, _translate("MainWindow", "Сталь"))
        self.comboBox_3_tube.setItemText(1, _translate("MainWindow", "Полипропилен"))
        self.checkBox_3_n_coef.setText(_translate("MainWindow", "Использовать нормативные коэффициенты"))
        self.label_40.setText(_translate("MainWindow", "5. Давление теплоносителя на вводе в здание / в ИТП"))
        self.comboBox_4_p_n.setItemText(0, _translate("MainWindow", "кПа"))
        self.comboBox_4_p_n.setItemText(1, _translate("MainWindow", "м вод. ст."))
        self.comboBox_4_p_n.setItemText(2, _translate("MainWindow", "атм"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Основные результаты"))
        self.label_16.setText(_translate("MainWindow", "1. Суммарные теплопотери по зданию, кВт"))
        self.label_18.setText(_translate("MainWindow", "2. Общая тепловая мощность СО, кВт"))
        self.label_21.setText(_translate("MainWindow", "3. Суммарный расход теплоносителя в СО, кг/ч"))
        self.label_22.setText(_translate("MainWindow", "4. Главное циркуляционное кольцо (ГЦК)"))
        self.label_23.setText(_translate("MainWindow", "5. Суммарные потери давления в ГЦК, кПа"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Дополнительные сведения"))
        self.label_24.setText(_translate("MainWindow", "1. Общая номинальная тепловая мощность СО, кВт"))
        self.label_25.setText(_translate("MainWindow", "2. Невязка теплового баланса, %"))
        self.label_26.setText(_translate("MainWindow", "3. Балансовый расход теплоносителя, кг/ч"))
        self.label_27.setText(_translate("MainWindow", "4. Невязка материального баланса, %"))
        self.pushButton_5_rest.setText(_translate("MainWindow", "Новый расчет"))
        self.pushButton_6_save.setText(_translate("MainWindow", "Сохранить \n"
"результаты"))
        self.pushButton_7_help.setText(_translate("MainWindow", "Руководство пользователя"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Основные данные"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Тип огр. констр."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Стороны света"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Длина ограждения, м"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ширина ограждения, м"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Количество элементов"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Теплопотери, Вт"))
        self.pushButton_add_row.setText(_translate("MainWindow", "Добавить \n"
"строку"))
        self.pushButton_2_room.setText(_translate("MainWindow", "Добавить \n"
"помещение"))
        self.pushButton_3_del_row.setText(_translate("MainWindow", "Удалить \n"
" строки"))
        self.pushButton_4_calc_h_loss.setText(_translate("MainWindow", "Рассчитать"))
        self.checkBox_inf.setText(_translate("MainWindow", "Учет инфильтрации\n"
" (+20%)"))
        self.checkBox_2_t_reg.setText(_translate("MainWindow", "Учет терморегул.\n"
" СП 60 п. 6.2.13\n"
" (+15%)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Расчет теплопотерь"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        self.pushButton_form_pr.setText(_translate("MainWindow", "Сформировать \n"
"таблицу"))
        self.pushButton_del_pr.setText(_translate("MainWindow", "Удалить \n"
"таблицу"))
        self.pushButton_calc_pr.setText(_translate("MainWindow", "Рассчитать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Расчет отопительных приборов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Гидравлический расчет"))

# Подключение интерфейса
class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.pushButton_2_room.clicked.connect(self.add_room)
        self.pushButton_add_row.clicked.connect(self.add_row)
        self.pushButton_3_del_row.clicked.connect(self.delete_rows)
        self.pushButton_4_calc_h_loss.clicked.connect(self.base_data)
        self.pushButton_4_calc_h_loss.clicked.connect(self.calc_process)
        self.pushButton_4_calc_h_loss.clicked.connect(self.sum_loss_heat)
        self.pushButton_4_calc_h_loss.clicked.connect(self.sum_loss_heat_build)
        self.pushButton_5_rest.clicked.connect(self.auto_test)
        self.checkBox_3_n_coef.stateChanged.connect(self.norm_coef)
        global room_number
        room_number = 1

    def add_room(self):
        global room_number

        self.num_symb = QtWidgets.QTableWidgetItem('№')
        self.num_symb.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.num_symb.setBackground(QtGui.QColor(85, 255, 255))
        self.num_symb.setFlags(QtCore.Qt.ItemIsEnabled)

        self.room_order = QtWidgets.QTableWidgetItem(str(room_number))
        self.room_order.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.room_order.setBackground(QtGui.QColor(85, 255, 255))

        self.room_name = QtWidgets.QTableWidgetItem('')
        self.room_name.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.room_name.setBackground(QtGui.QColor(170, 255, 127))

        self.t_vn_name = QtWidgets.QTableWidgetItem('tвн, °C')
        self.t_vn_name.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.t_vn_name.setBackground(QtGui.QColor(85, 255, 255))
        self.t_vn_name.setFlags(QtCore.Qt.ItemIsEnabled)

        self.t_vn = QtWidgets.QTableWidgetItem('')
        self.t_vn.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.t_vn.setBackground(QtGui.QColor(170, 255, 127))

        self.sum_room_heat_loss = QtWidgets.QTableWidgetItem('')
        self.sum_room_heat_loss.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.sum_room_heat_loss.setBackground(QtGui.QColor(85, 255, 255))
        self.sum_room_heat_loss.setFlags(QtCore.Qt.ItemIsEnabled)

        rowPosition = self.tableWidget.rowCount()
        if self.lineEdit_4_room.text() == "":
            self.tableWidget.insertRow(rowPosition)
            self.tableWidget.setItem(rowPosition, 0, self.num_symb)
            self.tableWidget.setItem(rowPosition, 1, self.room_order)
            self.tableWidget.setItem(rowPosition, 2, self.room_name)
            self.tableWidget.setItem(rowPosition, 3, self.t_vn_name)
            self.tableWidget.setItem(rowPosition, 4, self.t_vn)
            self.tableWidget.setItem(rowPosition, 5, self.sum_room_heat_loss)
            room_number += 1
        else:
            int_room = int(self.lineEdit_4_room.text())
            self.tableWidget.insertRow(int_room)
            self.tableWidget.setItem(int_room, 0, self.num_symb)
            self.tableWidget.setItem(int_room, 1, self.room_order)
            self.tableWidget.setItem(int_room, 2, self.room_name)
            self.tableWidget.setItem(int_room, 3, self.t_vn_name)
            self.tableWidget.setItem(int_room, 4, self.t_vn)
            self.tableWidget.setItem(int_room, 5, self.sum_room_heat_loss)
            room_number += 1
        self.tableWidget.resizeRowsToContents()
        self.tableWidget.resizeColumnsToContents()

    def add_row(self):
        self.combo_f_structure = QtWidgets.QComboBox()
        self.combo_f_structure.addItem('Пол I з.')
        self.combo_f_structure.addItem('Пол II з.')
        self.combo_f_structure.addItem('Пол III з.')
        self.combo_f_structure.addItem('Пол IV з.')
        self.combo_f_structure.addItem('Кровля')
        self.combo_f_structure.addItem('Н.С.')
        self.combo_f_structure.addItem('Н.С. (О)')
        self.combo_f_structure.addItem('Н.С. (Д)')
        self.combo_f_structure.addItem('Н.С. (О+Д)')
        self.combo_f_structure.currentIndexChanged.connect(self.combo_cond)

        self.combo_s_world = QtWidgets.QComboBox()
        self.combo_s_world.addItem('С')
        self.combo_s_world.addItem('В')
        self.combo_s_world.addItem('СЗ')
        self.combo_s_world.addItem('СВ')
        self.combo_s_world.addItem('Ю')
        self.combo_s_world.addItem('З')
        self.combo_s_world.addItem('ЮВ')
        self.combo_s_world.addItem('ЮЗ')
        self.combo_s_world.addItem('—')
        self.combo_s_world.setCurrentIndex(8)
        self.combo_s_world.currentIndexChanged.connect(self.side_world)

        self.room_len = QtWidgets.QTableWidgetItem('')
        self.room_len.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.room_wid = QtWidgets.QTableWidgetItem('')
        self.room_wid.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.block_quan = QtWidgets.QTableWidgetItem('1')
        self.block_quan.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.sum_heat_loss = QtWidgets.QTableWidgetItem('')
        self.sum_heat_loss.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.sum_heat_loss.setFlags(QtCore.Qt.ItemIsEnabled)

        rowPosition = self.tableWidget.rowCount()
        if self.lineEdit_3_add_row.text() == "":
            self.tableWidget.insertRow(rowPosition)
            self.tableWidget.setCellWidget(rowPosition, 0, self.combo_f_structure)
            self.tableWidget.setCellWidget(rowPosition, 1, self.combo_s_world)
            self.tableWidget.setItem(rowPosition, 2, self.room_len)
            self.tableWidget.setItem(rowPosition, 3, self.room_wid)
            self.tableWidget.setItem(rowPosition, 4, self.block_quan)
            self.tableWidget.setItem(rowPosition, 5, self.sum_heat_loss)
        else:
            int_row = int(self.lineEdit_3_add_row.text())
            self.tableWidget.insertRow(int_row)
            self.tableWidget.setCellWidget(int_row, 0, self.combo_f_structure)
            self.tableWidget.setCellWidget(int_row, 1, self.combo_s_world)
            self.tableWidget.setItem(int_row, 2, self.room_len)
            self.tableWidget.setItem(int_row, 3, self.room_wid)
            self.tableWidget.setItem(int_row, 4, self.block_quan)
            self.tableWidget.setItem(int_row, 5, self.sum_heat_loss)

        self.tableWidget.resizeRowsToContents()
        self.tableWidget.resizeColumnsToContents()

    def combo_cond(self):
        rowPosition = self.tableWidget.currentRow()+1

        self.room_len = QtWidgets.QTableWidgetItem('')
        self.room_len.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.room_len_1 = QtWidgets.QTableWidgetItem('')
        self.room_len_1.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.room_wid = QtWidgets.QTableWidgetItem('')
        self.room_wid.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.room_wid_1 = QtWidgets.QTableWidgetItem('')
        self.room_wid_1.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.block_quan = QtWidgets.QTableWidgetItem('1')
        self.block_quan.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.block_quan_1 = QtWidgets.QTableWidgetItem('1')
        self.block_quan_1.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.sum_heat_loss = QtWidgets.QTableWidgetItem('')
        self.sum_heat_loss.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.sum_heat_loss.setFlags(QtCore.Qt.ItemIsEnabled)

        self.sum_heat_loss_1 = QtWidgets.QTableWidgetItem('')
        self.sum_heat_loss_1.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.sum_heat_loss_1.setFlags(QtCore.Qt.ItemIsEnabled)

        self.room_window = QtWidgets.QTableWidgetItem('Окно')
        self.room_window.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.room_door = QtWidgets.QTableWidgetItem('Дверь')
        self.room_door.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)

        self.side_world_1 = QtWidgets.QTableWidgetItem('')
        self.side_world_1.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.side_world_1.setFlags(QtCore.Qt.ItemIsEnabled)

        self.side_world_2 = QtWidgets.QTableWidgetItem('')
        self.side_world_2.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
        self.side_world_2.setFlags(QtCore.Qt.ItemIsEnabled)

        self.current_item = self.tableWidget.cellWidget(self.tableWidget.currentRow(), self.tableWidget.currentColumn())
        self.side_item = self.tableWidget.cellWidget(self.tableWidget.currentRow(), self.tableWidget.currentColumn()+1)
        if isinstance(self.current_item, QtWidgets.QComboBox):
            cur_text = self.current_item.currentIndex()
            for i in range(5):
                if cur_text == i:
                    self.side_item.setCurrentIndex(8)

            if cur_text == 6:
                self.tableWidget.insertRow(rowPosition)
                self.tableWidget.setItem(rowPosition, 0, self.room_window)
                self.tableWidget.setItem(rowPosition, 1, self.side_world_1)
                self.tableWidget.item(rowPosition, 1).setText(self.tableWidget.cellWidget(rowPosition - 1, 1).currentText())
                self.tableWidget.setItem(rowPosition, 2, self.room_len)
                self.tableWidget.setItem(rowPosition, 3, self.room_wid)
                self.tableWidget.setItem(rowPosition, 4, self.block_quan)
                self.tableWidget.setItem(rowPosition, 5, self.sum_heat_loss)

            if cur_text == 7:
                self.tableWidget.insertRow(rowPosition)
                self.tableWidget.setItem(rowPosition, 0, self.room_door)
                self.tableWidget.setItem(rowPosition, 1, self.side_world_1)
                self.tableWidget.item(rowPosition, 1).setText(self.tableWidget.cellWidget(rowPosition - 1, 1).currentText())
                self.tableWidget.setItem(rowPosition, 2, self.room_len)
                self.tableWidget.setItem(rowPosition, 3, self.room_wid)
                self.tableWidget.setItem(rowPosition, 4, self.block_quan)
                self.tableWidget.setItem(rowPosition, 5, self.sum_heat_loss)

            if cur_text == 8:
                self.tableWidget.insertRow(rowPosition)
                self.tableWidget.setItem(rowPosition, 0, self.room_window)
                self.tableWidget.setItem(rowPosition, 1, self.side_world_1)
                self.tableWidget.item(rowPosition, 1).setText(self.tableWidget.cellWidget(rowPosition - 1, 1).currentText())
                self.tableWidget.setItem(rowPosition, 2, self.room_len)
                self.tableWidget.setItem(rowPosition, 3, self.room_wid)
                self.tableWidget.setItem(rowPosition, 4, self.block_quan)
                self.tableWidget.setItem(rowPosition, 5, self.sum_heat_loss)
                self.tableWidget.insertRow(rowPosition+1)
                self.tableWidget.setItem(rowPosition+1, 0, self.room_door)
                self.tableWidget.setItem(rowPosition+1, 1, self.side_world_2)
                self.tableWidget.item(rowPosition+1, 1).setText(self.tableWidget.cellWidget(rowPosition - 1, 1).currentText())
                self.tableWidget.setItem(rowPosition+1, 2, self.room_len_1)
                self.tableWidget.setItem(rowPosition+1, 3, self.room_wid_1)
                self.tableWidget.setItem(rowPosition+1, 4, self.block_quan_1)
                self.tableWidget.setItem(rowPosition+1, 5, self.sum_heat_loss_1)

    def side_world(self):
        current_item = self.tableWidget.cellWidget(self.tableWidget.currentRow(), self.tableWidget.currentColumn())
        side_item_1 = self.tableWidget.item(self.tableWidget.currentRow() + 1, self.tableWidget.currentColumn())
        side_item_2 = self.tableWidget.item(self.tableWidget.currentRow() + 2, self.tableWidget.currentColumn())
        if isinstance(side_item_1, QtWidgets.QTableWidgetItem):
            side_item_1.setText(current_item.currentText())
            if isinstance(side_item_2, QtWidgets.QTableWidgetItem):
                side_item_2.setText(current_item.currentText())

    def delete_rows(self):
        rowPosition = self.tableWidget.rowCount()-1
        if self.lineEdit_f_d_row.text() == "" or self.lineEdit_2_l_d_row.text() == "":
            self.tableWidget.removeRow(rowPosition)
        else:
            f_int_row = int(self.lineEdit_f_d_row.text()) - 1
            l_int_row = int(self.lineEdit_2_l_d_row.text())
            for i in range(f_int_row, l_int_row):
                self.tableWidget.removeRow(f_int_row)

    def norm_coef(self):
        if self.checkBox_3_n_coef.isChecked():
            self.lineEdit_9_ns.setText(str(0.47))
            self.lineEdit_12_wind.setText(str(1.59))
            self.lineEdit_16_door.setText(str(2.33))
            self.lineEdit_15_kr.setText(str(0.32))
            self.lineEdit_11_pol_1.setText(str(0.48))
            self.lineEdit_13_pol_2.setText(str(0.23))
            self.lineEdit_7_pol_3.setText(str(0.12))
            self.lineEdit_14_pol_4.setText(str(0.07))
        else:
            self.lineEdit_9_ns.clear()
            self.lineEdit_12_wind.clear()
            self.lineEdit_16_door.clear()
            self.lineEdit_15_kr.clear()
            self.lineEdit_11_pol_1.clear()
            self.lineEdit_13_pol_2.clear()
            self.lineEdit_7_pol_3.clear()
            self.lineEdit_14_pol_4.clear()

    def base_data(self):
        self.t_v_out = int(self.lineEdit_6_t_n.text())
        self.t1 = int(self.comboBox_t1.currentText())
        self.t2 = int(self.comboBox_2_t2.currentText())
        self.p1 = int(self.lineEdit_p_n.text())
        self.k_mass = (float(self.lineEdit_11_pol_1.text()), float(self.lineEdit_13_pol_2.text()), float(self.lineEdit_7_pol_3.text()),
                       float(self.lineEdit_14_pol_4.text()), float(self.lineEdit_15_kr.text()), float(self.lineEdit_9_ns.text()),
                       float(self.lineEdit_12_wind.text()), float(self.lineEdit_16_door.text()))

    def calc_process(self):
        for i in range(self.tableWidget.rowCount()):
            coef_str = 0
            coef_square = 0
            self.current_item = self.tableWidget.item(i, 0)
            self.current_side = self.tableWidget.item(i, 1)
            if isinstance(self.current_item, QtWidgets.QTableWidgetItem):
                self.current_item = self.tableWidget.item(i, 0)
                self.current_text = self.tableWidget.item(i, 0).text()
                if self.current_text == 'Окно':
                    self.k_tp = self.k_mass[6]
                if self.current_text == 'Дверь':
                    self.k_tp = self.k_mass[7]
            else:
                self.current_item = self.tableWidget.cellWidget(i, 0)
                self.current_text = self.tableWidget.cellWidget(i, 0).currentText()
                for m in range(4):
                    if self.current_item.currentIndex() == m:
                        coef_str = 1
                for m in range(6):
                    if self.current_item.currentIndex() == m:
                        self.k_tp = self.k_mass[m]
                for m in range(6, 9):
                    if self.current_item.currentIndex() == m:
                        self.k_tp = self.k_mass[5]
                if self.current_item.currentIndex() == 6 or self.current_item.currentIndex() == 7:
                    coef_square = 1
                if self.current_item.currentIndex() == 8:
                    coef_square = 2

            if isinstance(self.current_side, QtWidgets.QTableWidgetItem):
                self.current_side = self.tableWidget.item(i, 1)
                self.current_side_text = self.tableWidget.item(i, 1).text()
            else:
                self.current_side = self.tableWidget.cellWidget(i, 1)
                self.current_side_text = self.tableWidget.cellWidget(i, 1).currentText()

            if self.current_text == '№':
                self.delta_t = int(self.tableWidget.item(i, 4).text()) - self.t_v_out
            else:
                if coef_str == 1:
                    coef_struct = 1
                elif self.current_side_text == 'С' or self.current_side_text == 'В' or self.current_side_text == 'CЗ' or self.current_side_text == 'CВ':
                    coef_struct = 1.2
                elif self.current_side_text == 'Ю' or self.current_side_text == 'З' or self.current_side_text == 'ЮВ' or self.current_side_text == 'ЮЗ':
                    coef_struct = 1.15
                else:
                    coef_struct = 1.1
                if coef_square == 1:
                    self.square = float(self.tableWidget.item(i, 2).text()) * float(
                        self.tableWidget.item(i, 3).text() * int(self.tableWidget.item(i, 4).text())) - float(self.tableWidget.item(i+1, 2).text()) * float(
                        self.tableWidget.item(i+1, 3).text() * int(self.tableWidget.item(i+1, 4).text()))
                elif coef_square == 2:
                    self.square = float(self.tableWidget.item(i, 2).text()) * float(
                        self.tableWidget.item(i, 3).text() * int(self.tableWidget.item(i, 4).text())) - float(
                        self.tableWidget.item(i + 1, 2).text()) * float(
                        self.tableWidget.item(i + 1, 3).text() * int(self.tableWidget.item(i + 1, 4).text())) - float(
                        self.tableWidget.item(i + 2, 2).text()) * float(
                        self.tableWidget.item(i + 2, 3).text() * int(self.tableWidget.item(i + 2, 4).text()))
                else:
                    self.square = float(self.tableWidget.item(i, 2).text()) * float(self.tableWidget.item(i, 3).text() * int(self.tableWidget.item(i, 4).text()))
                self.heat_loss = round(self.k_tp * self.square * self.delta_t * coef_struct, 0)
                self.tableWidget.item(i, 5).setText(str(int(self.heat_loss)))

    def sum_loss_heat(self):
        self.sum_loss_h = 0
        if self.checkBox_inf.isChecked():
            coef_inf = 1.2
        else:
            coef_inf = 1
        if self.checkBox_2_t_reg.isChecked():
            coef_sp_60 = 1.15
        else:
            coef_sp_60 = 1
        for i in range(self.tableWidget.rowCount()):
            if i + 1 > self.tableWidget.rowCount():
                break
            if self.tableWidget.item(i, 3).text() == 'tвн, °C':
                a = i
            elif self.tableWidget.item(i, 3).text() != 'tвн, °C':
                self.sum_loss_h += int(self.tableWidget.item(i, 5).text())
                if i + 1 == self.tableWidget.rowCount() or self.tableWidget.item(i+1, 3).text() == 'tвн, °C':
                    self.tableWidget.item(a, 5).setText(str(int(round(coef_inf * coef_sp_60 * self.sum_loss_h, 0))))
                    self.sum_loss_h = 0

    def sum_loss_heat_build(self):
        loss_heat_build = 0
        for i in range(self.tableWidget.rowCount()):
            if self.tableWidget.item(i, 3).text() == 'tвн, °C':
                loss_heat_build += int(self.tableWidget.item(i, 5).text())
            if i + 1 == self.tableWidget.rowCount():
                self.lineEdit_17_sum_h_loss.setText(str(float(round(loss_heat_build / 1000, 2))))

    def auto_test(self):
        self.checkBox_3_n_coef.setChecked(True)
        self.lineEdit_6_t_n.setText(str(-24))
        self.lineEdit_p_n.setText(str(6000))
        self.add_room()
        self.room_name.setText('Кабинет')
        self.tableWidget.item(0, 4).setText(str(20))
        self.add_row()
        self.tableWidget.item(1, 2).setText('4')
        self.tableWidget.item(1, 3).setText('2')
        self.add_row()
        self.tableWidget.cellWidget(2, 0).setCurrentIndex(1)
        self.tableWidget.item(2, 2).setText('2')
        self.tableWidget.item(2, 3).setText('2')
        self.add_row()
        self.tableWidget.cellWidget(3, 0).setCurrentIndex(5)
        self.tableWidget.cellWidget(3, 1).setCurrentIndex(0)
        self.tableWidget.item(3, 2).setText('6')
        self.tableWidget.item(3, 3).setText('3')
        self.add_row()
        self.tableWidget.item(4, 2).setText('6')
        self.tableWidget.item(4, 3).setText('3')
        self.tableWidget.setCurrentCell(4, 0)
        self.tableWidget.cellWidget(4, 0).setCurrentIndex(6)
        self.tableWidget.cellWidget(4, 1).setCurrentIndex(6)
        self.add_row()
        self.room_len.setText('6')
        self.room_wid.setText('6')
        self.combo_f_structure.setCurrentIndex(4)
        self.lineEdit_f_d_row.setText('7')
        self.lineEdit_2_l_d_row.setText('7')
        self.delete_rows()
        self.tableWidget.item(5, 2).setText('1')
        self.tableWidget.item(5, 3).setText('1')

    def get_data_from_h_loss(self):


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())